version: '3.8'
services: 
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: roledb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes: 
      - ./volumes/data/db:/data/db
    restart: always